// SPDX-License-Identifier: Apache-2.0

package circtTests.stage

import chisel3._
import circt.stage.CIRCTStage
import circt.{emitSystemVerilog, getSystemVerilogString}

import firrtl.EmittedVerilogCircuitAnnotation
import firrtl.stage.{FirrtlFileAnnotation, OutputFileAnnotation}
import java.io.File
import java.io.{PrintWriter, Writer}

import org.scalatest.funspec.AnyFunSpec
import org.scalatest.matchers.should.Matchers

import scala.io.Source

class Bar extends RawModule {
  val sel = IO(Input(UInt(3.W)))
  val in = IO(Input(Vec(8, UInt(8.W))))
  val out = IO(Output(UInt(8.W)))
  out := in(sel)
}

class CIRCTStageSpec extends AnyFunSpec with Matchers {

  private def writeFile(file: File, string: String): Unit = {
    val writer = {
      file.getParentFile.mkdirs()
      new PrintWriter(file)
    }
    writer.write(string)
    writer.close()
  }

  describe("CIRCTStage") {

    it("should compile a FIRRTL file to Verilog") {

      val input =
        """|circuit Foo:
           |  module Foo:
           |    input a: UInt<1>
           |    output b: UInt<1>
           |    b <= not(a)
           |""".stripMargin

      val targetDir = new File("test_run_dir/CIRCTStage")
      val inputFile = new File(targetDir, "Foo.fir")

      writeFile(inputFile, input)

      val outputFile = new File(targetDir, "Foo.sv")
      outputFile.delete()

      val stage = new CIRCTStage

      stage.execute(
        Array(
          "--target",
          "systemverilog",
          "--target-dir",
          targetDir.toString,
          "--input-file",
          inputFile.toString
        ),
        Seq.empty
      )

      info(s"output file '$outputFile' was created")
      outputFile should exist

      info(s"file looks like Verilog")
      Source.fromFile(outputFile).getLines.mkString should include("endmodule")

    }

    it("circt.getVerilogString should emit SystemVerilog to string") {

      val sv = getSystemVerilogString(
        new ChiselStageSpec.Foo,
        Array("--show-registrations"),
        Array("--strip-debug-info")
      )
      sv should include("Generated by CIRCT")

    }

    it("circt.emitVerilog should support custom Chisel args and firtool options") {
      val targetDir = new File("test_run_dir/ChiselStageSpec/generated")

      val args: Array[String] = Array(
        "--target-dir",
        targetDir.toString
      )

      info(s"output contains a case statement using --lowering-options=disallowPackedArrays")
      emitSystemVerilog(
        new Bar,
        args,
        Array("--lowering-options=disallowPackedArrays")
      ).collectFirst {
        case EmittedVerilogCircuitAnnotation(a) => a
      }.get.value should include("case")

      val expectedOutput = new File(targetDir, "Bar.sv")
      expectedOutput should (exist)
      info(s"'$expectedOutput' exists")
    }
  }

}
